<?php
$this->headScript()->appendFile('/js/jquery.lightbox-0.5.min.js', 'text/javascript');
$this->headLink()->appendStylesheet('/css/jquery.lightbox-0.5.css')
?>


<?php echo $this->form; ?>

<br/>
<?php if ($this->data): ?>
<div id="gallery-photo">
    <div id="nav">
        <a href="#" id="page-pre" />&nbsp;&nbsp;<&nbsp;&nbsp;</a>
        <a href="#" id="page-first">Home</a>
        <a href="#" id="page-next" />&nbsp;&nbsp;>&nbsp;&nbsp;</a>
    </div>
    
    <div id="gallery">
        <ul>
            <li>
        <?php foreach ($this->data as $photo): ?>
        <li><a href="<?php echo $photo['url'];?>" title="<?php echo $photo['title']; ?>">
            <img src="<?php echo $photo['url']; ?>" />
        </a></li>
        <?php endforeach; ?>    
        </ul>    
    </div>
</div>



<?php endif; ?>

<script type="text/javascript">
$(document).ready(function(){
    $('#nav a').click(function(){
        var self = $(this),
            pageCol = $('#page'),
            page = pageCol.val(),
            button = $('#submit'),
            newPage;
        switch (self.attr('id')) {
            case 'page-first': 
                newPage = 1;
                break;
            case 'page-pre':
                newPage = ((page - 1) < 1) ? 1 : (page - 1);
                break;
            case 'page-next':
                newPage = parseInt(page) + 1;
                break;
        }
        pageCol.val(newPage);
        button.click();
        return false;
    });
    
    $('#reset').click(function(){
        window.location = '/';
        return false;
    });
    
     $('#gallery a').lightBox();
});
</script>