<!doctype html>
<html>
    <head>
        <meta name="language" content="en" />
        <meta charset="utf-8">
        <link rel="stylesheet" href="/css/style.css" />
        <script type="text/javascript" src="/js/jquery-1.7.1.min.js"></script>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>